<?php

namespace PDFBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Page2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Page2Repository extends EntityRepository
{
}
